# Generated by Django 6.0 on 2026-01-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Building_Name', models.CharField(max_length=50)),
                ('Room_Number', models.CharField(max_length=50)),
                ('Sector', models.IntegerField()),
                ('City', models.CharField(max_length=50)),
                ('Land_Mark', models.CharField(max_length=50)),
                ('Pincode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Favourite_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fav_Singer', models.CharField(max_length=50)),
                ('Fav_Food', models.CharField(max_length=50)),
                ('Fav_Teacher', models.CharField(max_length=50)),
                ('Fav_Car', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Middle_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('Contact_Number', models.IntegerField()),
                ('EMail_Address', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tech_Skills', models.CharField(max_length=50)),
                ('Non_Tech_Skills', models.CharField(max_length=50)),
                ('Sports_Skills', models.CharField(max_length=50)),
            ],
        ),
    ]
